services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: diary
      POSTGRES_PASSWORD: password
volumes:
  db-store:
